### PR TITLE
fix(aws vault): Fix default sanitizer hashcode append logic

### LINKED ISSUE #133: Sanitation Strategy in AWS Vault extension does not resolve manually created secrets
# Bug Report

## Describe the Bug
The resolveSecret(String key) method sanitizes the original key before fetching the secret value. While this works for secrets created using the AWS Vault extension, because the created secret key will be sanitized before storing it, it does not work for secrets created by other means (for example, manually created secrets).

### Expected Behavior
The Connector should be able to fetch any secret in SecretsManager

### Observed Behavior
Only secrets created by the AWS vault (these secrets will have their hash code appended) ca be fetched, using their original key.

## Steps to Reproduce
1. Go to any AWS account with a running setup of EDC with the AWS Secrets Manager vault extension.
2. Go to Secrets Manager and add a new secret named "test".
3. Update EDC's EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS environment variable to "test".
   3.1. This environment variable is an example of an alias to a required secret. Other environment variable that refer to a secret alias 
   that the EDC requires to fetch can be used to test as well.
4. Restart the controlplane and open logs
5. See that the controlplane tries to access "test_<hash_code>" and fails because that secret does not exist.

## Context Information
Tested on Tractus-X connector version 0.5.1

## Possible Implementation
For the time being, we implemented the extension, added a new "DummySanitationStrategy" that returns the original key unchanged and changed AwsSecretsManagerVault to use it instead of the default sanitation strategy. Since our EDC does not create any secret, no sanitation is required. I would suggest adding this "DummySanitationStrategy" and updating the extension to allow for the selection of the sanitation strategy through environment variable. This would allow for users to choose if they want to have their keys sanitized or not.

### PR DESCRIPTION
**Pull request by rafaelmagalhaes-ctw**
## What this PR changes/adds

This changes the logic on how an hashcode is appended to a key after it is sanitized, during secrets manager vault store/retrieve/delete methods.

## Why it does that

The current implementation of the default sanitizer strategy appends an hashcode to the secret key every time the store/retrieve/delete methods are used. While this has no impact for new secrets created by the vault, the vault fails to find existing secrets that were created previously either by AWS Console, CLI, another SDK, etc...
In such cases where the secret already exists, the sanization should have no effect in the given key.
The key should have an hashcode appended only when:
- It was changed because illegal characters where replaced;
- The key was shortened because it had more than 512 characters;

## Further notes

The tests where also adapted to be aligned with the changed logic.

## Linked Issue(s)

Closes #133

### CODE REVIEW

File: extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultDefaultSanitationStrategy.java [hunk 1]
```diff
@@ -25,34 +26,41 @@ public AwsSecretsManagerVaultDefaultSanitationStrategy(Monitor monitor) {
...
      */
     @Override
     public String sanitizeKey(String originalKey) {
         var key = originalKey;
-        if (originalKey.length() > 500) {
+        boolean originalKeyReplaced = false;
+
+        if (originalKey.length() > 512) {
+            //Substring to 500, to add the 12 char hashcode
             key = originalKey.substring(0, 500);
```
Comment (ndr-brt) [inline extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultDefaultSanitationStrategy.java:42]: I didn't get this 500/512 thing, looking at the tests seems like it's a sort of size limit for the key size, eventually it could be extracted as a constant called `KEY_SIZE_LIMIT` or something like that. 
The comment is outdated (please adapt the code to being able to talk for itself)

File: extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultDefaultSanitationStrategy.java [hunk 2]
```diff
@@ -25,34 +26,41 @@ public AwsSecretsManagerVaultDefaultSanitationStrategy(Monitor monitor) {
...
         }
+
         var sb = new StringBuilder();
-        boolean replacedIllegalCharacters = false;
         for (int i = 0; i < key.length(); i++) {
             var c = key.charAt(i);
             if (!Character.isLetterOrDigit(c) && c != '/' && c != '_' && c != '+' && c != '.' && c != '@' && c != '-') {
-                replacedIllegalCharacters = true;
+                originalKeyReplaced = true;
                 sb.append('-');
```
Comment (ndr-brt) [inline extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultDefaultSanitationStrategy.java:51]: the documentation says `_` but the code does `-`. Is this an error?

**Review by ndr-brt — CHANGES_REQUESTED** [review]

File: extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultDefaultSanitationStrategy.java (hunk 2 above)
Comment (rafaelmagalhaes-ctw) [reply extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultDefaultSanitationStrategy.java:51]: This logic is for replacing invalidad characters in the original key to "-". (ex: example#key, replaced to example-key)
The hashcode is appended afterwards.
