### PR TITLE
fix(dataplane): deserialize secret depending on content

### LINKED ISSUE #457: S3 data plane fails on non-temporary credentials in the vault
# Bug Report

## Describe the Bug

According to the S3 data plane's README, both `AwsSecretToken` and `AwsTemporarySecretToken` can be read from the vault and used for authentication. My tests have revealed that this is only possible for `AwsTemporarySecretToken` and will run into an error for `AwsSecretToken`. The combination of only `accessKeyId` and `secretAccessKey` (without session token) currently only works when putting the credentials directly into the data address.

### Expected Behavior

I can put either an `AwsSecretToken` or an `AwsTemporarySecretToken` into the vault and authentication with AWS works correctly during a transfer.

### Observed Behavior

If I put an `AwsSecretToken` into the vault and reference this in a data address, the authentication with AWS fails with message "sessionToken must not be null".

## Steps to Reproduce

1. Put a secret with AWS credentials into the vault with the following format: `{"edctype": "dataspaceconnector:secrettoken",  "accessKeyId": "<aws-access-key-id>", "secretAccessKey": "<aws-secret-access-key>"}`
2. Reference this secret in an asset's data address of type `AmazonS3` using the `keyName` property
3. Create other entities & do a negotiation
4. Initiate a transfer for that asset
5. See the following in the provider's error logs: 
> `SEVERE 2024-09-25T15:13:09.185936016 StateMachineManager [DataPlaneManagerImpl] error caught
> java.lang.NullPointerException: sessionToken must not be null.`

## Context Information

- Used version EDC 0.9.0
- OS: Linux/Ubuntu

## Possible Implementation

The issue lies in the `createS3ClientRequest` method of the `S3DataSourceFactory`. Here, the secret is read from the vault and deserialized directly to an `AwsTemporarySecretToken`. If the deserialization was successful, the `AwsTemporarySecretToken` instance will be used, and if the deserialization failed, `accessKeyId` and `secretAccessKey` are instead read from the data address directly. Since also `AwsSecretToken` can be deserialized to an `AwsTemporarySecretToken` (with `sessionToken=null`), the invalid `AwsTemporarySecretToken` is used, which causes the above mentioned error. 

Instead of always deserializing the secret to an `AwsTemporarySecretToken`, it should instead be deserialized to either an `AwsSecretToken` __or__ an `AwsTemporarySecretToken` depending on its content.

The same applies for the `S3DataSinkFactory`.

### PR DESCRIPTION
**Pull request by ronjaquensel**
## What this PR changes/adds

Deserializes the secret obtained from the vault to either an `AwsSecretToken` or an `AwsTemporarySecretToken` depending on whether it contains a `sessionToken` field or not.

## Why it does that

To allow both the usage of static and temporary credentials with the S3 data plane. Previously, the secret was always deserialized directly to an `AwsTemporarySecretToken`, which caused the transfer to fail if static credentials were used.

## Further notes

The code for deserializing the secret has been duplicated for `S3DataSourceFactory` and `S3DataSinkFactory` for now, as also the code for creating the S3 client request is duplicated. Refactoring to remove these duplications should be done in another PR.

## Linked Issue(s)

Closes #457

### CODE REVIEW

File: extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java [hunk 1]
```diff
@@ -128,4 +132,14 @@ private S3ClientRequest createS3ClientRequest(DataAddress address) {
             return S3ClientRequest.from(region, endpointOverride);
         }
     }
+    
+    private SecretToken deserializeSecretToken(String secret) {
+        var typeReference = new TypeReference<HashMap<String, Object>>() {};
+        var map = typeManager.readValue(secret, typeReference);
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java:138]: This was the old way of deserializing things, lately we stopped going through the `TypeManager` but we're using the `ObjectMapper` instance directly, by doing that it will enable to use the `readTree` method to read the tree (that can tell if the "sessionToken" exists) and then with the `treeToValue` the tree can be converted to the actual type.

File: extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java [hunk 2]
```diff
@@ -118,5 +123,14 @@ private S3ClientRequest createS3ClientRequest(DataAddress address) {
             return S3ClientRequest.from(region, endpointOverride);
         }
     }
-
+    
+    private SecretToken deserializeSecretToken(String secret) {
+        var typeReference = new TypeReference<HashMap<String, Object>>() {};
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java:128]: same

**Review by ndr-brt — COMMENTED** [review]
just a proposal about the deserialization process

**Review by ndr-brt — APPROVED** [review]
